# Generated by Django 5.1.6 on 2025-04-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_category_remove_product_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('retailer', 'Retailer'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
